command:
  - "uvicorn"
  - "backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"
env:
  - name: DATABRICKS_SERVING_ENDPOINT
    value: "stryker-pricing-models"
  - name: CATALOG_NAME
    value: "hls_amer_catalog"
  - name: SCHEMA_NAME
    value: "gold"
  - name: DATABRICKS_WAREHOUSE_ID
    value: ""
